<project xmlns="http://maven.apache.org/POM/4.0.0"> 
    <modelVersion>4.0.0</modelVersion> 
    <groupId>com.example</groupId> 
    <artifactId>jakartaee-mysql</artifactId> 
    <version>1.0</version> 
    <packaging>war</packaging> 
     <dependencies> 
        <dependency> 
            <groupId>jakarta.servlet</groupId> 
            <artifactId>jakarta.servlet-api</artifactId> 
            <version>5.0.0</version> 
            <scope>provided</scope> 
        </dependency> 
        <dependency> 
            <groupId>mysql</groupId> 
            <artifactId>mysql-connector-java</artifactId> 
            <version>8.0.33</version> 
        </dependency> 
        <dependency> 
            <groupId>javax.servlet</groupId> 
            <artifactId>jstl</artifactId> 
            <version>1.2</version> 
        </dependency> 
    </dependencies> 
</project> 